import type { Database } from "@/integrations/supabase/types";

export type Candidate = Database["public"]["Functions"]["buscar_candidatos"]["Returns"][number];
export type Sponsored = Database["public"]["Tables"]["sponsored_profiles"]["Row"];
export type Message = Database["public"]["Tables"]["messages"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Match = Database["public"]["Tables"]["matches"]["Row"];
export type Photo = Database["public"]["Tables"]["profile_photos"]["Row"];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "a1111111-1111-1111-1111-111111111111",
    display_name: "Marina Costa",
    idade: 24,
    gender: "mulher",
    bio: "Amo fotografia analógica, cafés especiais e explorar cantinhos secretos da cidade aos fins de semana. Apaixonada por jazz, vinil e boas conversas.",
    city: "São Paulo, SP",
    height_cm: 165,
    body_type: "curvilíneo",
    eye_color: "castanhos",
    hair_color: "castanho",
    signo: "Áries",
    elemento: "fogo",
    distance_km: 4.2,
    soft_score: 0.96,
    affinity: 96,
    shared_tags: ["fotografia", "café", "jazz", "viagens", "arte"],
    tags: ["fotografia", "café", "jazz", "viagens", "arte"],
    same_element: true,
  },
  {
    id: "b2222222-2222-2222-2222-222222222222",
    display_name: "Rafael Oliveira",
    idade: 27,
    gender: "homem",
    bio: "Engenheiro de software nos dias úteis e surfista no fim de semana. Se tiver trilha com vista pro mar e um pôr do sol bonito, pode me chamar.",
    city: "Rio de Janeiro, RJ",
    height_cm: 182,
    body_type: "atlético",
    eye_color: "pretos",
    hair_color: "preto",
    signo: "Gêmeos",
    elemento: "ar",
    distance_km: 8.5,
    soft_score: 0.91,
    affinity: 91,
    shared_tags: ["surf", "tecnologia", "trilha", "praia", "rock"],
    tags: ["surf", "tecnologia", "trilha", "praia", "rock"],
    same_element: false,
  },
  {
    id: "c3333333-3333-3333-3333-333333333333",
    display_name: "Camila Santos",
    idade: 25,
    gender: "mulher",
    bio: "Instrutora de yoga e apaixonada por livros de ficção científica e botânica. Procuro conexões leves e alguém para observar as estrelas.",
    city: "Belo Horizonte, MG",
    height_cm: 160,
    body_type: "magro",
    eye_color: "verdes",
    hair_color: "loiro",
    signo: "Leão",
    elemento: "fogo",
    distance_km: 12.0,
    soft_score: 0.88,
    affinity: 88,
    shared_tags: ["yoga", "leitura", "astronomia", "gastronomia"],
    tags: ["yoga", "leitura", "astronomia", "gastronomia", "meditação"],
    same_element: true,
  },
  {
    id: "d4444444-4444-4444-4444-444444444444",
    display_name: "Lucas Ferreira",
    idade: 29,
    gender: "homem",
    bio: "Chef de cozinha e apreciador de vinhos artesanais. Acredito que a melhor conversa acontece ao redor de uma mesa cheia de comida boa.",
    city: "Curitiba, PR",
    height_cm: 178,
    body_type: "médio",
    eye_color: "castanhos",
    hair_color: "castanho",
    signo: "Virgem",
    elemento: "terra",
    distance_km: 15.3,
    soft_score: 0.94,
    affinity: 94,
    shared_tags: ["gastronomia", "vinho", "cinema", "jazz"],
    tags: ["gastronomia", "vinho", "cinema", "jazz", "viagens"],
    same_element: false,
  },
  {
    id: "e5555555-5555-5555-5555-555555555555",
    display_name: "Ana Ribeiro",
    idade: 23,
    gender: "mulher",
    bio: "Designer gráfica e ilustradora. Viciada em feiras de vinil, exposições de arte contemporânea e gatinhos.",
    city: "Porto Alegre, RS",
    height_cm: 168,
    body_type: "curvilíneo",
    eye_color: "mel",
    hair_color: "ruivo",
    signo: "Libra",
    elemento: "ar",
    distance_km: 6.7,
    soft_score: 0.92,
    affinity: 92,
    shared_tags: ["design", "cinema", "ilustração", "café"],
    tags: ["design", "cinema", "ilustração", "café", "gatos"],
    same_element: false,
  },
  {
    id: "f6666666-6666-6666-6666-666666666666",
    display_name: "Pedro Almeida",
    idade: 28,
    gender: "homem",
    bio: "Músico e produtor musical. Toco violão, baixo e teclado. Salvador é minha energia e busco alguém para dividir fones de ouvido.",
    city: "Salvador, BA",
    height_cm: 175,
    body_type: "forte",
    eye_color: "pretos",
    hair_color: "preto",
    signo: "Áries",
    elemento: "fogo",
    distance_km: 18.0,
    soft_score: 0.89,
    affinity: 89,
    shared_tags: ["música", "shows", "violão", "praia", "samba"],
    tags: ["música", "shows", "violão", "praia", "samba"],
    same_element: true,
  },
  {
    id: "77777777-7777-7777-7777-777777777777",
    display_name: "Julia Mendes",
    idade: 26,
    gender: "mulher",
    bio: "Nutricionista esportiva e triatleta. Amo correr ao nascer do sol na praia e planejar viagens de mochila pelo mundo.",
    city: "Florianópolis, SC",
    height_cm: 170,
    body_type: "atlético",
    eye_color: "castanhos",
    hair_color: "preto",
    signo: "Aquário",
    elemento: "ar",
    distance_km: 9.4,
    soft_score: 0.95,
    affinity: 95,
    shared_tags: ["corrida", "praia", "viagens", "fitness", "natureza"],
    tags: ["corrida", "praia", "viagens", "fitness", "natureza"],
    same_element: false,
  },
  {
    id: "88888888-8888-8888-8888-888888888888",
    display_name: "Thiago Lima",
    idade: 30,
    gender: "homem",
    bio: "Arquiteto apaixonado por traços modernistas, museus e degustação de cervejas artesanais. Conversas profundas garantidas.",
    city: "Brasília, DF",
    height_cm: 185,
    body_type: "médio",
    eye_color: "castanhos",
    hair_color: "castanho",
    signo: "Virgem",
    elemento: "terra",
    distance_km: 11.2,
    soft_score: 0.87,
    affinity: 87,
    shared_tags: ["arquitetura", "design", "cerveja artesanal", "museus"],
    tags: ["arquitetura", "design", "cerveja artesanal", "museus", "fotografia"],
    same_element: false,
  },
  {
    id: "99999999-9999-9999-9999-999999999999",
    display_name: "Beatriz Souza",
    idade: 24,
    gender: "mulher",
    bio: "Bióloga marinha e mergulhadora autônoma. Amo a vida sob as ondas, acampamentos sob o céu estrelado e documentários da natureza.",
    city: "Recife, PE",
    height_cm: 164,
    body_type: "atlético",
    eye_color: "azuis",
    hair_color: "loiro",
    signo: "Escorpião",
    elemento: "água",
    distance_km: 14.5,
    soft_score: 0.93,
    affinity: 93,
    shared_tags: ["mergulho", "natureza", "biologia", "praia", "viagens"],
    tags: ["mergulho", "natureza", "biologia", "praia", "viagens"],
    same_element: false,
  },
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    display_name: "Gabriel Martins",
    idade: 28,
    gender: "homem",
    bio: "Fotógrafo de vida selvagem e montanhista. Adoro acampar nas serras, café feito no fogareiro e o som da chuva na barraca.",
    city: "Campinas, SP",
    height_cm: 180,
    body_type: "atlético",
    eye_color: "castanhos",
    hair_color: "castanho",
    signo: "Sagitário",
    elemento: "fogo",
    distance_km: 5.8,
    soft_score: 0.90,
    affinity: 90,
    shared_tags: ["fotografia", "trilha", "escalada", "natureza", "café"],
    tags: ["fotografia", "trilha", "escalada", "natureza", "café"],
    same_element: true,
  },
];

export const MOCK_SPONSORED: Sponsored[] = [
  {
    id: "10000000-0000-0000-0000-000000000001",
    active: true,
    brand_name: "Café Reserva Especial",
    categoria: "Gastronomia & Encontros",
    headline: "O primeiro encontro perfeito começa com um bom café",
    tagline: "Ambiente intimista e cafés premiados",
    description: "Ganhe 20% de desconto no combo casal em qualquer uma de nossas cafeterias selecionadas.",
    coupon_code: "AFFINITY20",
    coupon_text: "20% OFF no primeiro café a dois",
    cta_label: "Resgatar Desconto",
    cta_url: "https://example.com/reserva-cafe",
    city: "São Paulo, SP",
    latitude: -23.5505,
    longitude: -46.6333,
    tags: ["café", "encontros", "gastronomia"],
    accent: "#eb5e28",
    created_at: new Date().toISOString(),
  },
  {
    id: "10000000-0000-0000-0000-000000000002",
    active: true,
    brand_name: "Trilhas & Aventura Brasil",
    categoria: "Lazer ao Ar Livre",
    headline: "Conecte-se com a natureza a dois",
    tagline: "Passeios ecológicos e experiências inesquecíveis",
    description: "Roteiros exclusivos para casais e duplas de aventureiros com guia credenciado.",
    coupon_code: "TRILHA15",
    coupon_text: "15% de desconto no primeiro passeio",
    cta_label: "Ver Roteiros",
    cta_url: "https://example.com/trilhas",
    city: "Rio de Janeiro, RJ",
    latitude: -22.9068,
    longitude: -43.1729,
    tags: ["aventura", "natureza", "trilhas", "ecoturismo"],
    accent: "#10b981",
    created_at: new Date().toISOString(),
  },
];

export interface MockMatchData {
  match: Match;
  profile: Profile;
  photos: Photo[];
  messages: Message[];
}

export const MOCK_MATCHES_MAP: Record<string, MockMatchData> = {
  "11111111-0000-0000-0000-000000000001": {
    match: {
      id: "11111111-0000-0000-0000-000000000001",
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      last_message_at: null,
      user_a: "me",
      user_b: "a1111111-1111-1111-1111-111111111111",
    },
    profile: {
      id: "a1111111-1111-1111-1111-111111111111",
      display_name: "Marina Costa",
      birth_date: "2001-03-25",
      gender: "mulher",
      seeking: ["homem", "mulher"],
      bio: "Amo fotografia analógica, cafés especiais e explorar cantinhos secretos da cidade.",
      height_cm: 165,
      body_type: "curvilíneo",
      eye_color: "castanhos",
      hair_color: "castanho",
      city: "São Paulo, SP",
      latitude: -23.5505,
      longitude: -46.6333,
      location_source: null,
      min_age: 22,
      max_age: 35,
      max_distance_km: 50,
      signo: "Áries",
      elemento: "fogo",
      onboarding_complete: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    photos: [],
    messages: [
      {
        id: "msg-1-1",
        match_id: "11111111-0000-0000-0000-000000000001",
        sender_id: "a1111111-1111-1111-1111-111111111111",
        body: "Oi! Que bom que demos match! Também vi que você curte fotografia e café!",
        created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
        read_at: new Date().toISOString(),
      },
    ],
  },
  "22222222-0000-0000-0000-000000000002": {
    match: {
      id: "22222222-0000-0000-0000-000000000002",
      created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
      last_message_at: null,
      user_a: "me",
      user_b: "c3333333-3333-3333-3333-333333333333",
    },
    profile: {
      id: "c3333333-3333-3333-3333-333333333333",
      display_name: "Camila Santos",
      birth_date: "2000-07-28",
      gender: "mulher",
      seeking: ["homem"],
      bio: "Instrutora de yoga e apaixonada por livros e botânica.",
      height_cm: 160,
      body_type: "magro",
      eye_color: "verdes",
      hair_color: "loiro",
      city: "Belo Horizonte, MG",
      latitude: -19.9167,
      longitude: -43.9345,
      location_source: null,
      min_age: 24,
      max_age: 36,
      max_distance_km: 60,
      signo: "Leão",
      elemento: "fogo",
      onboarding_complete: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    photos: [],
    messages: [],
  },
  "33333333-0000-0000-0000-000000000003": {
    match: {
      id: "33333333-0000-0000-0000-000000000003",
      created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
      last_message_at: new Date(Date.now() - 1800000).toISOString(),
      user_a: "me",
      user_b: "b2222222-2222-2222-2222-222222222222",
    },
    profile: {
      id: "b2222222-2222-2222-2222-222222222222",
      display_name: "Rafael Oliveira",
      birth_date: "1998-06-15",
      gender: "homem",
      seeking: ["mulher"],
      bio: "Engenheiro de software nos dias úteis e surfista no fim de semana.",
      height_cm: 182,
      body_type: "atlético",
      eye_color: "pretos",
      hair_color: "preto",
      city: "Rio de Janeiro, RJ",
      latitude: -22.9068,
      longitude: -43.1729,
      location_source: null,
      min_age: 23,
      max_age: 35,
      max_distance_km: 80,
      signo: "Gêmeos",
      elemento: "ar",
      onboarding_complete: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    photos: [],
    messages: [
      {
        id: "msg-3-1",
        match_id: "33333333-0000-0000-0000-000000000003",
        sender_id: "b2222222-2222-2222-2222-222222222222",
        body: "E aí! Curti muito o seu perfil, também adoro trilhas e praia!",
        created_at: new Date(Date.now() - 1800000).toISOString(),
        read_at: null,
      },
    ],
  },
  "44444444-0000-0000-0000-000000000004": {
    match: {
      id: "44444444-0000-0000-0000-000000000004",
      created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
      last_message_at: new Date(Date.now() - 3600000 * 3).toISOString(),
      user_a: "me",
      user_b: "77777777-7777-7777-7777-777777777777",
    },
    profile: {
      id: "77777777-7777-7777-7777-777777777777",
      display_name: "Julia Mendes",
      birth_date: "1999-02-10",
      gender: "mulher",
      seeking: ["homem"],
      bio: "Nutricionista esportiva e triatleta. Amo correr ao nascer do sol.",
      height_cm: 170,
      body_type: "atlético",
      eye_color: "castanhos",
      hair_color: "preto",
      city: "Florianópolis, SC",
      latitude: -27.5954,
      longitude: -48.548,
      location_source: null,
      min_age: 24,
      max_age: 38,
      max_distance_km: 80,
      signo: "Aquário",
      elemento: "ar",
      onboarding_complete: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    photos: [],
    messages: [
      {
        id: "msg-4-1",
        match_id: "44444444-0000-0000-0000-000000000004",
        sender_id: "me",
        body: "Qual sua praia favorita em Floripa?",
        created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
        read_at: new Date().toISOString(),
      },
      {
        id: "msg-4-2",
        match_id: "44444444-0000-0000-0000-000000000004",
        sender_id: "77777777-7777-7777-7777-777777777777",
        body: "A Praia Mole bem cedinho é maravilhosa! Você já conhece?",
        created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
        read_at: new Date().toISOString(),
      },
    ],
  },
};

export function isValidUUID(uuid: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(uuid);
}

export function getMockMatchData(matchId: string): MockMatchData | null {
  if (MOCK_MATCHES_MAP[matchId]) {
    return MOCK_MATCHES_MAP[matchId];
  }
  // If matchId is a candidate ID, synthesize a match
  const candidate = MOCK_CANDIDATES.find((c) => c.id === matchId);
  if (candidate) {
    return {
      match: {
        id: matchId,
        created_at: new Date().toISOString(),
        last_message_at: null,
        user_a: "me",
        user_b: candidate.id,
      },
      profile: {
        id: candidate.id,
        display_name: candidate.display_name,
        birth_date: "1998-01-01",
        gender: candidate.gender,
        seeking: [],
        bio: candidate.bio,
        height_cm: candidate.height_cm,
        body_type: candidate.body_type,
        eye_color: candidate.eye_color,
        hair_color: candidate.hair_color,
        city: candidate.city,
        latitude: null,
        longitude: null,
        location_source: null,
        min_age: 18,
        max_age: 50,
        max_distance_km: 100,
        signo: candidate.signo,
        elemento: candidate.elemento,
        onboarding_complete: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      photos: [],
      messages: [
        {
          id: `msg-${candidate.id}`,
          match_id: matchId,
          sender_id: candidate.id,
          body: `Olá! Fiquei muito feliz com o nosso match! Adorei seus interesses em comum.`,
          created_at: new Date().toISOString(),
          read_at: null,
        },
      ],
    };
  }
  return null;
}
